POST http://localhost:3333/register
Content-Type: application/json
Allow: POST

{
    "name": "Henrique Adhmann Pires",
    "username": "henrique.pires",
    "email": "henrique.pires@gmail.com",
    "pass": "123456",
    "adm": true
}

###

GET http://localhost:3333/login?search=henrique.pires@gmail.com

###

PUT http://localhost:3333/users/a294bd99-b0ff-4371-b86f-197a4ea25ddf
Content-Type: application/json

{
    "name": "Henrique Adhmann Pires",
    "username": "henrique.pires",
    "email": "henrique.pires@gmail.com",
    "pass": "123456",
    "adm": false
}

###

DELETE http://localhost:3333/users/5d99f908-6d2b-40f0-9595-3cb6b7d8e043
